<div id="nav-topo">
    <div class="navbar-inner">
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-collapse">
                    <ul class="nav navbar-nav">
                        {MENU}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </nav>
        </div>
    </div>
</div>